version: "3.3"

services:

  grocy:
    image: lscr.io/linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./grocy/data:/config
    ports:
      - "8200:80"
    restart: unless-stopped
    